/**
 * WebSocket message protocol.
 *
 * Every message that flows between client and server is typed here.
 * Both sides import from this file — no room for mismatches.
 *
 * Client → Server messages
 * Server → Client messages
 */

// ── Scenario context — generated by ScenarioAgent ─────────────────────────
export interface ScenarioContext {
  personaName:    string;  // e.g. "Maria"
  personaRole:    string;  // e.g. "Café Barista"
  setting:        string;  // e.g. "A cozy café in Madrid"
  systemPrompt:   string;  // full instructions for the AI
  openingMessage: string;  // first thing the AI says (in target language)
}

// ── Client → Server ────────────────────────────────────────────────────────
export type ClientMessage =
  | {
      type: "start_session";
      sessionId:       string;
      language:        string;
      level:           string;
      scenarioRequest: string;  // e.g. "ordering coffee" or custom text
    }
  | {
      type:    "send_message";
      content: string;
    }
  | {
      type: "end_session";
    }
  | {
      type: "ping";
    };

// ── Server → Client ────────────────────────────────────────────────────────
export type ServerMessage =
  | {
      type:     "session_ready";
      scenario: ScenarioContext;
    }
  | {
      // Streaming token — append to the current in-progress message
      type:  "token";
      token: string;
    }
  | {
      // Stream finished — the full message is now in the DB
      type:    "message_done";
      message: {
        id:        string;
        role:      "assistant";
        content:   string;
        createdAt: string;
      };
    }
  | {
      // A user message was saved — send back so frontend has the DB id
      type:    "user_message_saved";
      message: {
        id:        string;
        role:      "user";
        content:   string;
        createdAt: string;
      };
    }
  | {
      type: "session_ended";
    }
  | {
      type:    "error";
      code:    string;
      message: string;
    }
  | {
      type: "pong";
    };